Fix tests/seige/urlgen for non-macs
Should address https://github.com/influxdb/influxdb/issues/1437

diff --git a/tests/siege/urlgen b/tests/siege/urlgen
--- a/tests/siege/urlgen
+++ b/tests/siege/urlgen
@@ -1,7 +1,21 @@
 #!/bin/sh -e
 
 # Calculate start time as unix timestamp.
-TIME=`date -j -f "%b %d %T %Z %Y" "Jan 01 00:00:00 EDT 2000" "+%s"`
+
+PLATFORM=`uname`
+_date () {
+    if [ "$PLATFORM" = "Darwin" ] ; then
+        date -j -f "%b %d %T %Z %Y" "$1" "+%s"
+    elif [ "$PLATFORM" = "Linux" ] ; then
+        date -d "$1" "+%s"
+    else
+        echo "I don't know if your date can read a format and a time, failing"
+        exit 99
+    fi
+}
+
+TIME=`time  "Jan 01 00:00:00 EDT 2000"`
+
 
 # Set defaults.
 INTERVAL=1      # 1s
@@ -50,7 +64,7 @@ for i in `seq 1 $NUMPOINTS`;
 do
 	# Move forward the current time.
 	let TIME=TIME+INTERVAL
-	TIMESTAMP=`date -j -f "%s" $TIME +"%Y-%m-%dT%H:%M:%SZ"`
+	TIMESTAMP=`_date $TIME`
 
 	# Generate a URL for each series.
 	for series in `seq 1 $NUMSERIES`;
@@ -58,5 +72,3 @@ do
 		echo 'http://localhost:8086/write POST {"database" : "db", "retentionPolicy" : "raw", "points": [{"name": "cpu", "tags": {"host": "server'$series'"}, "timestamp": "'$TIMESTAMP'","values": {"value": 100}}]}'
 	done
 done
-
-
