build: add guards against using secrets in forked PR builds

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -38,20 +38,23 @@ workflows:
       - grace_daily:
           requires:
             - build
+          filters:
+            branches:
+              # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
+              ignore: /pull\/[0-9]+/
       - litmus_daily:
           requires:
             - build
           filters:
             branches:
-              only:
-                - /^(?!pull\/).*$/
+              # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
+              ignore: /pull\/[0-9]+/
       - litmus_integration:
           requires:
             - build
           filters:
             branches:
-              only:
-                - "2.0"
+              only: "2.0"
 
   release:
     jobs:
@@ -134,6 +137,20 @@ orbs:
   browser-tools: circleci/browser-tools@1.1
 
 commands:
+  # Log into quay.io, with a pre-check to ensure we aren't running from a forked PR.
+  quay_login:
+    steps:
+      - run:
+          name: Ensure not running from a fork
+          command: |
+            if [ -n "$CIRCLE_PR_NUMBER" ]; then
+              echo 'Error: build from fork detected, exiting!'
+              exit 1
+            fi
+      - run:
+          name: Log into Quay
+          command: docker login -u "$QUAY_USER" -p $QUAY_PASS quay.io
+
   # Install system dependencies needed to run a native build of influxd
   install_core_deps:
     steps:
@@ -159,6 +176,24 @@ commands:
       publish_release:
         type: boolean
     steps:
+      - when:
+          condition: << parameters.publish_release >>
+          steps:
+            - run:
+                name: Ensure not running from a fork
+                command: |
+                  if [ -n "$CIRCLE_PR_NUMBER" ]; then
+                    echo 'Error: release from fork detected, exiting!'
+                    exit 1
+                  fi
+            - run:
+                name: Import GPG key
+                command: |
+                  echo -e "$GPG_PRIVATE_KEY" > private.key
+                  gpg --batch --import private.key
+            - run:
+                name: Log into Quay
+                command: docker login -u "$QUAY_USER" -p $QUAY_PASS quay.io
       - run:
           name: Set GOPATH
           # Machine executors use a different GOPATH from the cimg/go Docker executors.
@@ -222,11 +257,6 @@ commands:
               lzma-dev \
               zlib1g-dev
       - run:
-          name: Import GPG key
-          command: |
-            echo -e "$GPG_PRIVATE_KEY" > private.key
-            gpg --batch --import private.key
-      - run:
           name: Install cross-compilers
           environment:
             MUSL_VERSION: 1.1.24
@@ -285,7 +315,7 @@ commands:
                 name: Build release
                 # `goreleaser release --skip-publish` builds Docker images, but doesn't push them.
                 # As opposed to `goreleaser build`, which stops before building Dockers.
-                command: goreleaser --debug release --skip-publish -p 1 --rm-dist --skip-validate
+                command: goreleaser --debug release --skip-publish --skip-sign -p 1 --rm-dist --skip-validate
       - when:
           condition: << parameters.publish_release >>
           steps:
@@ -603,9 +633,6 @@ jobs:
           name: Restore Yarn Cache
           keys:
             - yarn-deps-lock-{{ checksum "ui/yarn.lock" }}
-      - run:
-          name: Docker Login
-          command: docker login -u "$QUAY_USER" -p $QUAY_PASS quay.io
       - install_core_deps
       - run_goreleaser:
           publish_release: false
@@ -637,9 +664,7 @@ jobs:
           name: Restore Yarn Cache
           keys:
             - yarn-deps-lock-{{ checksum "ui/yarn.lock" }}
-      - run:
-          name: Docker Login
-          command: docker login -u "$QUAY_USER" -p $QUAY_PASS quay.io
+      - quay_login
       - install_core_deps
       - run_goreleaser:
           publish_release: true
@@ -687,7 +712,7 @@ jobs:
     steps:
       - attach_workspace:
           at: ~/project
-      - run: docker login -u=$QUAY_USER -p=$QUAY_PASS quay.io
+      - quay_login
       - run: docker run --entrypoint "./run_litmus_tests_oss.sh" -e ONE_TEST=src/cloud/rest_api/smoke/test_smoke.py -e BINARYPATH=/Litmus/result/bin/linux/influxd -e BOLTPATH=/Litmus/result/influxd_test/influxd.bolt -e ENGINEPATH=/Litmus/result/influxd_test --net host -v /var/run/docker.sock:/var/run/docker.sock -v ~/project:/Litmus/result quay.io/influxdb/litmus:latest
       - run:
           name: Litmus Smoke Tests Success
@@ -709,7 +734,7 @@ jobs:
     steps:
       - attach_workspace:
           at: ~/project
-      - run: docker login -u=$QUAY_USER -p=$QUAY_PASS quay.io
+      - quay_login
       - run: docker run --entrypoint "./run_litmus_tests_oss.sh" -e TEST_LIST=tests_lists/gateway_api_tests.list -e INFLUXPATH=/Litmus/result/bin/linux/influx -e BINARYPATH=/Litmus/result/bin/linux/influxd -e BOLTPATH=/tmp/influxd_test/influxd.bolt -e ENGINEPATH=/tmp/influxd_test --net host -v /var/run/docker.sock:/var/run/docker.sock -v ~/project:/Litmus/result quay.io/influxdb/litmus:latest
       - run:
           name: Litmus Integration Tests Success
@@ -730,7 +755,7 @@ jobs:
     steps:
       - attach_workspace:
           at: ~/project
-      - run: docker login -u=$QUAY_USER -p=$QUAY_PASS quay.io
+      - quay_login
       - run:
           command: ./bin/linux/influxd --store=memory --log-level=debug
           background: true
