ci: migrate to self-hosted circleci runners

diff --git a/.circleci/scripts/validate b/.circleci/scripts/validate
--- a/.circleci/scripts/validate
+++ b/.circleci/scripts/validate
@@ -5,7 +5,7 @@ set -o errexit \
 
 usage() {
   cat <<'EOF'
-usage: validate [type] [path]
+usage: validate [arch] [type] [path]
 
 Program:
     This application performs sanity checks on the provided InfluxDB
@@ -14,6 +14,8 @@ Program:
     performs specific checks relevant only to InfluxDB.
 
 Options:
+    arch    "amd" or "arm". Used with type and path to find
+            the correct binary to install.
     type    Must be "deb" or "rpm". This option instructs the
             application to use the package manager associated
             with "type".
@@ -21,12 +23,16 @@ Options:
 EOF
 }
 
-if [[ ! "${1:-}" ]] || [[ ! "${2:-}" ]]
+if [[ ! "${1:-}" ]] || [[ ! "${2:-}" ]] || [[ ! "${3:-}" ]]
 then
   (usage) && exit 1
 fi
-PACKAGE_TYPE="${1}"
-PACKAGE_PATH="${2}"
+PACKAGE_ARCH="${2}"
+PACKAGE_TYPE="${2}"
+PACKAGE_PATH="${3}"
+
+bin=$(find $PACKAGE_PATH -name "*${PACKAGE_ARCH}.${PACKAGE_TYPE}")
+[ ! -f $bin ] && echo "unable to find ${PACKAGE_TYPE} in ${PACKAGE_PATH}" && exit 1
 
 install_deb() {
   # When installing the package, ensure that the latest repository listings
@@ -38,23 +44,23 @@ install_deb() {
   # "apt-get install" should be used instead of "dpkg -i", because "dpkg"
   # does not resolve dependencies. "apt-get" requires that the package
   # path looks like a path (either fullpath or prefixed with "./").
-  apt-get install -y binutils "$(realpath "${PACKAGE_PATH}")"
+  apt-get install -y binutils "${1}}"
 }
 
 install_rpm() {
   # see "install_deb" for "update"
   yum update -y
   yum install -y binutils
-  yum localinstall -y "$(realpath "${PACKAGE_PATH}")"
+  yum localinstall -y "${1}"
 }
 
 case ${PACKAGE_TYPE}
 in
   deb)
-    (install_deb)
+    (install_deb "${bin}")
     ;;
   rpm)
-    (install_rpm)
+    (install_rpm "${bin}")
     ;;
 esac
 
